services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${USER}/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins_agent:
    image: jenkins/ssh-agent:jdk17
    container_name: agent1
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBKEY}
